@startuml
'https://plantuml.com/class-diagram
class Animal{
    AnimalSound getSound()
}
class Dog extends Animal{
    Woofing getSound()
}



class Woofing extends AnimalSound {
}


class AnimalSound  {
}


@enduml